BEGIN READ ONLY;
SELECT 'MASCO role identities and ESCO codes' AS check_name, count(*)=655 AS count_ok, md5(string_agg(r.role_id || chr(31) || r.masco_code || chr(31) || r.role_title || chr(31) || r.esco_code,E'\n' ORDER BY r.role_id COLLATE "C"))='e4d249525d08ad34a073b5a9a20b9cd5' AS content_ok FROM rerouteher.roles r JOIN rerouteher.dataset_metadata m ON m.metadata_key='d13_masco2020_rebuilt_20260830.mapping.'||r.role_id
UNION ALL
SELECT 'ESCO display titles' AS check_name, count(*)=655 AS count_ok, md5(string_agg((m.metadata_value->>'role_id') || chr(31) || (m.metadata_value->>'chosen_esco_code') || chr(31) || (m.metadata_value->>'chosen_esco_title'),E'\n' ORDER BY (m.metadata_value->>'role_id') COLLATE "C"))='27e826933d5f82c81a579f1e54cbcb48' AS content_ok FROM rerouteher.dataset_metadata m WHERE starts_with(m.metadata_key,'d13_masco2020_rebuilt_20260830.mapping.')
UNION ALL
SELECT 'Title Case canonical skills and definitions' AS check_name, count(*)=6080 AS count_ok, md5(string_agg(s.skill_id || chr(31) || s.canonical_name || chr(31) || coalesce(s.definition,'') || chr(31) || s.skill_type,E'\n' ORDER BY s.skill_id COLLATE "C"))='2699ca3afff3522a3f72fc30ba26218f' AS content_ok FROM rerouteher.skill_taxonomy s JOIN rerouteher.dataset_metadata m ON m.metadata_key='d13_masco2020_rebuilt_20260830.skill_type.'||s.skill_id
UNION ALL
SELECT 'Lowercase aliases with provenance' AS check_name, count(*)=37654 AS count_ok, md5(string_agg(s.skill_id || chr(31) || s.alias || chr(31) || s.alias_source,E'\n' ORDER BY s.skill_id COLLATE "C",s.alias COLLATE "C"))='3445711dde01b351d838193fc50e5aee' AS content_ok FROM rerouteher.skill_aliases s JOIN rerouteher.dataset_metadata m ON m.metadata_key='d13_masco2020_rebuilt_20260830.skill_type.'||s.skill_id
UNION ALL
SELECT 'Role-skill labels types and weights' AS check_name, count(*)=41024 AS count_ok, md5(string_agg(s.role_id || chr(31) || s.skill_id || chr(31) || s.skill_name || chr(31) || s.skill_type || chr(31) || s.importance::integer::text,E'\n' ORDER BY s.role_id COLLATE "C",s.skill_id COLLATE "C"))='c1251551ef9e7fead1dbe9c08d30722e' AS content_ok FROM rerouteher.role_skills s JOIN rerouteher.dataset_metadata m ON m.metadata_key='d13_masco2020_rebuilt_20260830.mapping.'||s.role_id
UNION ALL
SELECT 'Preserved original ESCO comparisons' AS check_name, count(*)=657 AS count_ok, md5(string_agg(coalesce(m.metadata_value->>'source_current_role_id','') || chr(31) || coalesce(m.metadata_value->>'d13_esco_code','') || chr(31) || coalesce(m.metadata_value->>'d13_esco_title','') || chr(31) || coalesce(m.metadata_value->>'d11_esco_comparison_codes','') || chr(31) || coalesce(m.metadata_value->>'d11_esco_comparison_titles',''),E'\n' ORDER BY (m.metadata_value->>'source_current_role_id') COLLATE "C"))='5de9c85551a654cb2827eb558db6dad6' AS content_ok FROM rerouteher.dataset_metadata m WHERE starts_with(m.metadata_key,'d13_masco2020_rebuilt_20260830.source_esco.');
COMMIT;
